// Balast i Ocieplenie — katalog sprzętu i akweny.
// Copyright (c) 2026 Maciej Korzeniowski. Wszelkie prawa zastrzeżone / All rights reserved.
// Kopiowanie i utwory zależne wymagają pisemnej zgody autora — zobacz LICENSE.
// ===== Katalog sprzętu =====
// Wartości pływalności: "szacunek" = wyliczone z fizyki / typowych danych, nie z pomiaru producenta.
const SZ = {
  mares: ['2','3','4','5','6','7','8'],                    // pianki Mares: rozmiary liczbowe
  maresBoot: ['XS 38-39','S 39-40','M 40-41','L 41-42','XL 43','2XL 44-45','3XL 45-46'],  // buty Mares: sklepowa tabela EU
  maresGlove: ['XS','S','M','L','XL','2XL'],               // rękawice Mares: producent
  maresFin: ['S','R','XL'],                                // płetwy Mares z otwartą piętą: producent (R = Regular)
  boot: ['36','37','38','39','40','41','42','43','44','45','46','47'],
  fin: ['S','M','L','XL'],
  finJet: ['S','M','L','XL','2XL'],            // Scubapro Jet Fin
  finHollis: ['R','XL','2XL'],                 // Hollis F1: Regular, XL, XXL
  cressi: ['XS/1','S/2','M/3','L/4','XL/5','XXL/6','XXXL/7'],
  suit: ['XS','S','M','L','XL','2XL','3XL'],   // pianki: typowy zakres dla dorosłych
  dry: ['S','M','ML','L','LT','XL','2XL'],     // suche: dochodzą kroje wydłużone
  bcd: ['XS','S','M','L','XL','2XL'],
  glove: ['XS','S','M','L','XL','2XL'],
  hood: ['S','M','L','XL'],
  under: ['S','M','L','XL','2XL'],
  fe: ['S','MS','M','ML','L','LT','XL','XXL'],
  santi: ['S','M','ML','L','LT','XL','XXL','MTF'],
  avatar: ['S','M','L','XL','XXL','na miarę'],
  harness: ['S','M','L','XL','uniwersalny'],
  one: ['uniwersalny']
};
const CATALOG = [
  // --- Pianki mokre i półsuche ---
  {id:'mares-reef-3', cat:'wetsuit', brand:'Mares', model:'Reef 3 mm', p:{t:3, cover:'full'}, sizes:SZ.mares, src:'producent (grubość)'},
  {id:'mares-reef-shorty-25', cat:'wetsuit', brand:'Mares', model:'Reef Shorty 2,5 mm', p:{t:2.5, cover:'shorty'}, sizes:SZ.mares, src:'producent (grubość)'},
  {id:'mares-flexa-543', cat:'wetsuit', brand:'Mares', model:'Flexa 5.4.3', p:{t:5, tl:4, cover:'full'}, sizes:SZ.mares, src:'producent (grubość)'},
  {id:'mares-flexa-865', cat:'wetsuit', brand:'Mares', model:'Flexa 8.6.5', p:{t:8, tl:6, cover:'full'}, sizes:SZ.mares, src:'producent (grubość)'},
  {id:'mares-evo-5', cat:'wetsuit', brand:'Mares', model:'Evolution 5 mm', p:{t:5, cover:'full'}, sizes:SZ.mares, src:'producent (grubość)'},
  {id:'mares-evo-7', cat:'wetsuit', brand:'Mares', model:'Evolution 7 mm', p:{t:7, cover:'full'}, sizes:SZ.mares, src:'producent (grubość)'},
  {id:'mares-protherm-87', cat:'wetsuit', brand:'Mares', model:'Pro Therm 8/7 półsucha, kaptur', p:{t:8, tl:7, cover:'full', semi:true, hood:true}, sizes:SZ.mares, src:'producent (grubość)'},
  {id:'cressi-morea-3', cat:'wetsuit', brand:'Cressi', model:'Morea 3 mm', p:{t:3, cover:'full'}, sizes:SZ.cressi, src:'producent (grubość)'},
  {id:'cressi-fast-5', cat:'wetsuit', brand:'Cressi', model:'Fast 5 mm', p:{t:5, cover:'full'}, sizes:SZ.cressi, src:'producent (grubość)'},
  {id:'cressi-fast-7', cat:'wetsuit', brand:'Cressi', model:'Fast 7 mm', p:{t:7, cover:'full'}, sizes:SZ.cressi, src:'producent (grubość)'},
  {id:'cressi-castoro-7', cat:'wetsuit', brand:'Cressi', model:'Castoro 7 mm (dwuczęściowa)', p:{t:7, cover:'full'}, sizes:SZ.cressi, src:'producent (grubość)'},
  {id:'cressi-lontra-7', cat:'wetsuit', brand:'Cressi', model:'Lontra 7 mm półsucha', p:{t:7, cover:'full', semi:true, hood:true}, sizes:SZ.cressi, src:'producent (grubość)'},
  {id:'sp-def-3', cat:'wetsuit', brand:'Scubapro', model:'Definition 3 mm', p:{t:3, cover:'full'}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'sp-def-5', cat:'wetsuit', brand:'Scubapro', model:'Definition 5 mm', p:{t:5, cover:'full'}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'sp-def-65', cat:'wetsuit', brand:'Scubapro', model:'Definition 6.5 mm', p:{t:6.5, cover:'full'}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'sp-everflex-32', cat:'wetsuit', brand:'Scubapro', model:'Everflex YULEX 3/2', p:{t:3, tl:2, cover:'full'}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'sp-everflex-54', cat:'wetsuit', brand:'Scubapro', model:'Everflex YULEX 5/4', p:{t:5, tl:4, cover:'full'}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'sp-everflex-75', cat:'wetsuit', brand:'Scubapro', model:'Everflex YULEX 7/5', p:{t:7, tl:5, cover:'full'}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'sp-novascotia-75', cat:'wetsuit', brand:'Scubapro', model:'Novascotia 7.5 półsucha', p:{t:7.5, cover:'full', semi:true, hood:true}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'fe-proteus-3', cat:'wetsuit', brand:'Fourth Element', model:'Proteus II 3 mm', p:{t:3, cover:'full'}, sizes:SZ.fe, src:'producent (grubość)'},
  {id:'fe-proteus-5', cat:'wetsuit', brand:'Fourth Element', model:'Proteus II 5 mm', p:{t:5, cover:'full'}, sizes:SZ.fe, src:'producent (grubość)'},
  {id:'fe-proteus-7', cat:'wetsuit', brand:'Fourth Element', model:'Proteus II 7 mm', p:{t:7, cover:'full'}, sizes:SZ.fe, src:'producent (grubość)'},
  {id:'gen-shorty-3', cat:'wetsuit', brand:'Ogólne', model:'Shorty 3 mm', p:{t:3, cover:'shorty'}, sizes:SZ.one, src:'szacunek'},
  {id:'gen-longjohn-5', cat:'wetsuit', brand:'Ogólne', model:'Long john 5 mm', p:{t:5, cover:'longjohn'}, sizes:SZ.one, src:'szacunek'},
  // --- Ocieplacze mokre ---
  {id:'mares-flexacore', cat:'over', brand:'Mares', model:'Flexa Core 3/4 z kapturem', p:{t:3, cover:'overhood', hood:true}, sizes:SZ.mares, src:'producent (głównie 3 mm, wstawki 4 mm, kaptur)'},
  {id:'gen-vest-hood-3', cat:'over', brand:'Ogólne', model:'Kamizelka z kapturem 3 mm', p:{t:3, cover:'vest', hood:true}, sizes:SZ.one, src:'szacunek'},
  {id:'gen-vest-hood-5', cat:'over', brand:'Ogólne', model:'Kamizelka z kapturem 5 mm', p:{t:5, cover:'vest', hood:true}, sizes:SZ.one, src:'szacunek'},
  {id:'gen-shorty-over-2', cat:'over', brand:'Ogólne', model:'Shorty ocieplacz 2 mm', p:{t:2, cover:'shorty'}, sizes:SZ.one, src:'szacunek'},
  // --- Kaptury, rękawice, buty ---
  {id:'gen-hood-3', cat:'hood', brand:'Ogólne', model:'Kaptur 3 mm', p:{t:3, cover:'hood', hood:true}, sizes:SZ.one, src:'szacunek'},
  {id:'gen-hood-5', cat:'hood', brand:'Ogólne', model:'Kaptur 5 mm', p:{t:5, cover:'hood', hood:true}, sizes:SZ.one, src:'szacunek'},
  {id:'gen-hood-7', cat:'hood', brand:'Ogólne', model:'Kaptur 7 mm', p:{t:7, cover:'hood', hood:true}, sizes:SZ.one, src:'szacunek'},
  {id:'gen-gloves-3', cat:'gloves', brand:'Ogólne', model:'Rękawice 3 mm', p:{t:3, cover:'gloves'}, sizes:SZ.one, src:'szacunek'},
  {id:'gen-gloves-5', cat:'gloves', brand:'Ogólne', model:'Rękawice 5 mm', p:{t:5, cover:'gloves'}, sizes:SZ.one, src:'szacunek'},
  {id:'mares-flexa-boots-5', cat:'boots', brand:'Mares', model:'Buty Flexa 5 mm', p:{t:5, cover:'boots'}, sizes:SZ.maresBoot, src:'producent (grubość)'},
  {id:'gen-boots-3', cat:'boots', brand:'Ogólne', model:'Buty 3 mm', p:{t:3, cover:'boots'}, sizes:SZ.one, src:'szacunek'},
  {id:'gen-boots-7', cat:'boots', brand:'Ogólne', model:'Buty 7 mm', p:{t:7, cover:'boots'}, sizes:SZ.one, src:'szacunek'},
  // --- Suche skafandry ---
  {id:'santi-elite', cat:'dry', brand:'Santi', model:'E.Lite+ (trylaminat)', p:{shell:'trilam', b:0.3}, sizes:SZ.santi, src:'szacunek'},
  {id:'santi-emotion', cat:'dry', brand:'Santi', model:'E.Motion+ (trylaminat)', p:{shell:'trilam', b:0.3}, sizes:SZ.santi, src:'szacunek'},
  {id:'avatar-101', cat:'dry', brand:'Avatar', model:'101 (membrana 4-warstwowa)', p:{shell:'membrane', b:0.4}, sizes:SZ.avatar, src:'szacunek'},
  {id:'avatar-102', cat:'dry', brand:'Avatar', model:'102 Airon (trylaminat)', p:{shell:'trilam', b:0.3}, sizes:SZ.avatar, src:'szacunek'},
  {id:'sp-evertech', cat:'dry', brand:'Scubapro', model:'Evertech Dry Breathable', p:{shell:'membrane', b:0.4}, sizes:SZ.dry, src:'szacunek'},
  {id:'sp-everdry4', cat:'dry', brand:'Scubapro', model:'Everdry 4 (neopren 4 mm)', p:{shell:'neo', t:4}, sizes:SZ.dry, src:'szacunek'},
  {id:'bare-aquatrek', cat:'dry', brand:'Bare', model:'Aqua Trek 1 (trylaminat)', p:{shell:'trilam', b:0.3}, sizes:SZ.dry, src:'szacunek'},
  {id:'gen-crushed', cat:'dry', brand:'Ogólne', model:'Neopren zgnieciony', p:{shell:'crushed', b:1.5}, sizes:SZ.one, src:'szacunek'},
  // --- Ocieplacze do suchego ---
  {id:'santi-flex80', cat:'under', brand:'Santi', model:'Flex 80', p:{g:2, tmin:14}, sizes:SZ.santi, src:'szacunek; zakres temp. orientacyjny'},
  {id:'santi-flex190', cat:'under', brand:'Santi', model:'Flex 190', p:{g:4, tmin:7}, sizes:SZ.santi, src:'szacunek; 7–14 °C wg sklepów'},
  {id:'santi-bz200', cat:'under', brand:'Santi', model:'BZ200', p:{g:5, tmin:5}, sizes:SZ.santi, src:'szacunek'},
  {id:'santi-bz400x', cat:'under', brand:'Santi', model:'BZ400X', p:{g:7, tmin:2}, sizes:SZ.santi, src:'szacunek; <7 °C wg sklepów'},
  {id:'avatar-901', cat:'under', brand:'Avatar', model:'901', p:{g:4, tmin:8}, sizes:SZ.avatar, src:'szacunek'},
  {id:'avatar-902', cat:'under', brand:'Avatar', model:'902', p:{g:6, tmin:4}, sizes:SZ.avatar, src:'szacunek'},
  {id:'fe-arctic', cat:'under', brand:'Fourth Element', model:'Arctic (góra + dół)', p:{g:5, tmin:5}, sizes:SZ.fe, src:'szacunek'},
  // --- Kamizelki (jacket, hybryda) ---
  {id:'mares-quantum', cat:'bcd', brand:'Mares', model:'Quantum', p:{b:1.2}, sizes:SZ.bcd, src:'szacunek'},
  {id:'mares-prestige', cat:'bcd', brand:'Mares', model:'Prestige', p:{b:1.0}, sizes:SZ.bcd, src:'szacunek'},
  {id:'mares-bolt', cat:'bcd', brand:'Mares', model:'Bolt SLS', p:{b:0.8}, sizes:SZ.bcd, src:'szacunek'},
  {id:'sp-hydros', cat:'bcd', brand:'Scubapro', model:'Hydros Pro', p:{b:0.5}, sizes:SZ.bcd, src:'szacunek'},
  {id:'sp-knighthawk', cat:'bcd', brand:'Scubapro', model:'Knighthawk', p:{b:0.8}, sizes:SZ.bcd, src:'szacunek'},
  {id:'sp-level', cat:'bcd', brand:'Scubapro', model:'Level', p:{b:1.0}, sizes:SZ.bcd, src:'szacunek'},
  {id:'sp-go', cat:'bcd', brand:'Scubapro', model:'Go (podróżny)', p:{b:0.6}, sizes:SZ.bcd, src:'szacunek'},
  {id:'cressi-aquaride', cat:'bcd', brand:'Cressi', model:'Aquaride', p:{b:1.0}, sizes:SZ.bcd, src:'szacunek'},
  {id:'cressi-travelight', cat:'bcd', brand:'Cressi', model:'Travelight', p:{b:0.6}, sizes:SZ.bcd, src:'szacunek'},
  {id:'cressi-start', cat:'bcd', brand:'Cressi', model:'Start', p:{b:1.0}, sizes:SZ.bcd, src:'szacunek'},
  {id:'gen-rental-jacket', cat:'bcd', brand:'Ogólne', model:'Jacket z wypożyczalni', p:{b:1.0}, sizes:SZ.one, src:'szacunek'},
  // --- Skrzydła z płytą ---
  {id:'xdeep-zeos28', cat:'wing', brand:'XDEEP', model:'Zeos 28 (13 kg)', p:{plate:'alu'}, sizes:SZ.one, src:'szacunek z wybranej płyty'},
  {id:'xdeep-zeos38', cat:'wing', brand:'XDEEP', model:'Zeos 38 (17 kg)', p:{plate:'alu'}, sizes:SZ.one, src:'szacunek z wybranej płyty'},
  {id:'xdeep-zen', cat:'wing', brand:'XDEEP', model:'Zen', p:{plate:'alu'}, sizes:SZ.one, src:'szacunek z wybranej płyty'},
  {id:'xdeep-ghost', cat:'wing', brand:'XDEEP', model:'Ghost', p:{plate:'alu'}, sizes:SZ.one, src:'szacunek z wybranej płyty'},
  {id:'tecline-peanut21', cat:'wing', brand:'Tecline', model:'Peanut 21', p:{plate:'alu'}, sizes:SZ.one, src:'szacunek z wybranej płyty'},
  {id:'tecline-peanut28', cat:'wing', brand:'Tecline', model:'Peanut 28', p:{plate:'alu'}, sizes:SZ.one, src:'szacunek z wybranej płyty'},
  {id:'mares-xr-trim', cat:'wing', brand:'Mares', model:'XR-Rec Trim', p:{plate:'alu'}, sizes:SZ.one, src:'szacunek z wybranej płyty'},
  {id:'mares-xr-hv', cat:'wing', brand:'Mares', model:'XR HV Single', p:{plate:'alu'}, sizes:SZ.one, src:'szacunek z wybranej płyty'},
  {id:'mares-xr-ice', cat:'wing', brand:'Mares', model:'XR-Rec Ice Single', p:{plate:'alu'}, sizes:SZ.one, src:'szacunek z wybranej płyty'},
  // --- Butle (be = wyporność pusta z zaworem w morzu 1,025; vd = objętość wypierana) ---
  {id:'st-10-232', cat:'tank', brand:'Stal', model:'10 l / 232 bar', p:{vol:10, mat:'stal', be:-1.0, vd:11.7}, sizes:SZ.one, src:'szacunek (typowe butle EU)'},
  {id:'st-12-232', cat:'tank', brand:'Stal', model:'12 l / 232 bar', p:{vol:12, mat:'stal', be:-1.4, vd:13.8}, sizes:SZ.one, src:'szacunek (typowe butle EU)'},
  {id:'st-12-300', cat:'tank', brand:'Stal', model:'12 l / 300 bar', p:{vol:12, mat:'stal', be:-2.9, vd:14.3}, sizes:SZ.one, src:'szacunek (typowe butle EU)'},
  {id:'st-15-232', cat:'tank', brand:'Stal', model:'15 l / 232 bar', p:{vol:15, mat:'stal', be:-1.6, vd:17.3}, sizes:SZ.one, src:'szacunek (typowe butle EU)'},
  {id:'al-s80', cat:'tank', brand:'Aluminium', model:'S80 11,1 l / 207 bar', p:{vol:11.1, mat:'alu', be:1.8, vd:15.7}, sizes:SZ.one, src:'wypiera ~15,6 l, masa ~14,3 kg'},
  {id:'al-s100', cat:'tank', brand:'Aluminium', model:'S100 13,2 l / 232 bar', p:{vol:13.2, mat:'alu', be:1.4, vd:18.5}, sizes:SZ.one, src:'szacunek'},
  {id:'al-15', cat:'tank', brand:'Aluminium', model:'15 l / 200 bar', p:{vol:15, mat:'alu', be:2.2, vd:20.5}, sizes:SZ.one, src:'szacunek'},
  // Twinset = dwie butle + manifold i obejmy (~3 kg stali, która sama wypiera ~0,4 l),
  // więc pusty ciągnie w dół wyraźnie mocniej niż suma dwóch pojedynczych.
  {id:'tw-2x10-232', cat:'tank', brand:'Twinset', model:'2 × 10 l / 232 bar (stal)', p:{n:2, vol:20, mat:'stal', be:-4.6, vd:23.8}, sizes:SZ.one, src:'szacunek (dwie butle, manifold i obejmy)'},
  {id:'tw-2x12-232', cat:'tank', brand:'Twinset', model:'2 × 12 l / 232 bar (stal)', p:{n:2, vol:24, mat:'stal', be:-5.4, vd:28.0}, sizes:SZ.one, src:'szacunek (dwie butle, manifold i obejmy)'},
  {id:'tw-2x12-300', cat:'tank', brand:'Twinset', model:'2 × 12 l / 300 bar (stal)', p:{n:2, vol:24, mat:'stal', be:-8.4, vd:29.0}, sizes:SZ.one, src:'szacunek (dwie butle, manifold i obejmy)'},
  {id:'tw-2x7-300', cat:'tank', brand:'Twinset', model:'2 × 7 l / 300 bar (stal)', p:{n:2, vol:14, mat:'stal', be:-5.2, vd:17.4}, sizes:SZ.one, src:'szacunek (dwie butle, manifold i obejmy)'},
  {id:'tw-2xs80', cat:'tank', brand:'Twinset', model:'2 × S80 11,1 l / 207 bar (aluminium)', p:{n:2, vol:22.2, mat:'alu', be:0.8, vd:32.0}, sizes:SZ.one, src:'szacunek (dwie butle, manifold i obejmy)'},
  // --- Butle stage: dokładane do podstawowej, nie zamiast niej ---
  {id:'stg-al-s80', cat:'stage', brand:'Aluminium', model:'S80 11,1 l / 207 bar (stage)', p:{vol:11.1, mat:'alu', be:1.5, vd:15.7}, sizes:SZ.one, src:'szacunek (butla z zaczepami)'},
  {id:'stg-al-57', cat:'stage', brand:'Aluminium', model:'5,7 l / 207 bar (stage)', p:{vol:5.7, mat:'alu', be:0.6, vd:8.4}, sizes:SZ.one, src:'szacunek (butla z zaczepami)'},
  {id:'stg-al-7', cat:'stage', brand:'Aluminium', model:'7 l / 200 bar (stage)', p:{vol:7, mat:'alu', be:0.7, vd:10.2}, sizes:SZ.one, src:'szacunek (butla z zaczepami)'},
  {id:'stg-st-7', cat:'stage', brand:'Stal', model:'7 l / 232 bar (stage)', p:{vol:7, mat:'stal', be:-1.2, vd:8.6}, sizes:SZ.one, src:'szacunek (butla z zaczepami)'},

  {id:'mares-flexa-hood-65', cat:'hood', brand:'Mares', model:'Kaptur Flexa 6.5 mm', p:{t:6.5, cover:'hood', hood:true}, sizes:SZ.hood, src:'producent (grubość)'},
  {id:'mares-flexa-gloves-5', cat:'gloves', brand:'Mares', model:'Rękawice Flexa Fit 5 mm', p:{t:5, cover:'gloves'}, sizes:SZ.maresGlove, src:'producent (grubość)'},
  {id:'sp-everflex-hood-5', cat:'hood', brand:'Scubapro', model:'Kaptur Everflex 5/3 mm', p:{t:5, cover:'hood', hood:true}, sizes:SZ.hood, src:'producent (grubość)'},
  {id:'sp-everflex-gloves-5', cat:'gloves', brand:'Scubapro', model:'Rękawice Everflex 5 mm', p:{t:5, cover:'gloves'}, sizes:SZ.glove, src:'producent (grubość)'},
  {id:'cressi-hood-5', cat:'hood', brand:'Cressi', model:'Kaptur 5 mm', p:{t:5, cover:'hood', hood:true}, sizes:SZ.hood, src:'producent (grubość)'},
  {id:'cressi-gloves-5', cat:'gloves', brand:'Cressi', model:'Rękawice High Stretch 5 mm', p:{t:5, cover:'gloves'}, sizes:SZ.glove, src:'producent (grubość)'},
  // ===== Bare =====
  {id:'bare-velocity-3', cat:'wetsuit', brand:'Bare', model:'Velocity Ultra 3 mm', p:{t:3, cover:'full'}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'bare-velocity-5', cat:'wetsuit', brand:'Bare', model:'Velocity Ultra 5 mm', p:{t:5, cover:'full'}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'bare-velocity-7', cat:'wetsuit', brand:'Bare', model:'Velocity Ultra 7 mm', p:{t:7, cover:'full'}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'bare-reactive-5', cat:'wetsuit', brand:'Bare', model:'Reactive 5 mm', p:{t:5, cover:'full'}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'bare-velocity-semi-7', cat:'wetsuit', brand:'Bare', model:'Velocity Semi-Dry 7 mm, kaptur', p:{t:7, cover:'full', semi:true, hood:true}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'bare-uw-hood-7', cat:'hood', brand:'Bare', model:'Ultrawarmth kaptur 7 mm', p:{t:7, cover:'hood', hood:true}, sizes:SZ.hood, src:'producent (grubość)'},
  {id:'bare-uw-gloves-5', cat:'gloves', brand:'Bare', model:'Ultrawarmth rękawice 5 mm', p:{t:5, cover:'gloves'}, sizes:SZ.glove, src:'producent (grubość)'},
  {id:'bare-uw-boots-7', cat:'boots', brand:'Bare', model:'Ultrawarmth buty 7 mm', p:{t:7, cover:'boots', mass:1100}, sizes:SZ.boot, src:'grubość: producent; masa: szacunek'},
  {id:'bare-velocity-boots-5', cat:'boots', brand:'Bare', model:'Velocity buty 5 mm', p:{t:5, cover:'boots', mass:900}, sizes:SZ.boot, src:'grubość: producent; masa: szacunek'},
  {id:'bare-xmission', cat:'dry', brand:'Bare', model:'X-Mission Evolution (trylaminat)', p:{shell:'trilam', b:0.3}, sizes:SZ.dry, src:'szacunek'},
  {id:'bare-expedition-hd2', cat:'dry', brand:'Bare', model:'Expedition HD2 (trylaminat)', p:{shell:'trilam', b:0.4}, sizes:SZ.dry, src:'szacunek'},
  {id:'bare-sb-mid', cat:'under', brand:'Bare', model:'SB System Mid Layer', p:{g:4, tmin:7}, sizes:SZ.under, src:'szacunek'},
  {id:'bare-uw-base', cat:'under', brand:'Bare', model:'Ultrawarmth Base Layer', p:{g:2, tmin:13}, sizes:SZ.under, src:'szacunek'},
  // ===== Aqualung =====
  {id:'al-dynaflex-3', cat:'wetsuit', brand:'Aqualung', model:'Dynaflex 3 mm', p:{t:3, cover:'full'}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'al-dynaflex-55', cat:'wetsuit', brand:'Aqualung', model:'Dynaflex 5.5 mm', p:{t:5.5, cover:'full'}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'al-dynaflex-7', cat:'wetsuit', brand:'Aqualung', model:'Dynaflex 7 mm', p:{t:7, cover:'full'}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'al-hydroflex-3', cat:'wetsuit', brand:'Aqualung', model:'HydroFlex 3 mm', p:{t:3, cover:'full'}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'al-hydroflex-5', cat:'wetsuit', brand:'Aqualung', model:'HydroFlex 5 mm', p:{t:5, cover:'full'}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'al-solafx-8', cat:'wetsuit', brand:'Aqualung', model:'SolAfx 8/7 półsucha, kaptur', p:{t:8, tl:7, cover:'full', semi:true, hood:true}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'al-superzip-5', cat:'boots', brand:'Aqualung', model:'Superzip Ergo buty 5 mm', p:{t:5, cover:'boots', mass:1000}, sizes:SZ.boot, src:'grubość: producent; masa: szacunek'},
  {id:'al-echozip-5', cat:'boots', brand:'Aqualung', model:'Echozip buty 5 mm', p:{t:5, cover:'boots', mass:850}, sizes:SZ.boot, src:'grubość: producent; masa: szacunek'},
  {id:'al-gloves-5', cat:'gloves', brand:'Aqualung', model:'Superstretch rękawice 5 mm', p:{t:5, cover:'gloves'}, sizes:SZ.glove, src:'producent (grubość)'},
  {id:'al-hood-5', cat:'hood', brand:'Aqualung', model:'Kaptur 5/3 mm', p:{t:5, cover:'hood', hood:true}, sizes:SZ.hood, src:'producent (grubość)'},
  {id:'al-blizzard', cat:'dry', brand:'Aqualung', model:'Blizzard Pro (neopren 4 mm)', p:{shell:'neo', t:4}, sizes:SZ.dry, src:'szacunek'},
  {id:'al-fusion', cat:'dry', brand:'Aqualung', model:'Fusion Sport (membrana)', p:{shell:'membrane', b:0.8}, sizes:SZ.dry, src:'szacunek'},
  {id:'al-prohd', cat:'bcd', brand:'Aqualung', model:'Pro HD', p:{b:1.2}, sizes:SZ.bcd, src:'szacunek'},
  {id:'al-axiom', cat:'bcd', brand:'Aqualung', model:'Axiom', p:{b:1.0}, sizes:SZ.bcd, src:'szacunek'},
  {id:'al-rogue', cat:'bcd', brand:'Aqualung', model:'Rogue', p:{b:0.8}, sizes:SZ.bcd, src:'szacunek'},
  {id:'al-wave', cat:'bcd', brand:'Aqualung', model:'Wave', p:{b:0.9}, sizes:SZ.bcd, src:'szacunek'},
  {id:'al-zuma', cat:'bcd', brand:'Aqualung', model:'Zuma (podróżny)', p:{b:0.5}, sizes:SZ.bcd, src:'szacunek'},
  {id:'al-outlaw', cat:'bcd', brand:'Aqualung', model:'Outlaw', p:{b:0.6}, sizes:SZ.bcd, src:'szacunek'},
  // ===== Tusa =====
  {id:'tusa-liberator', cat:'bcd', brand:'Tusa', model:'Liberator Sigma II', p:{b:1.0}, sizes:SZ.bcd, src:'szacunek'},
  {id:'tusa-libero', cat:'bcd', brand:'Tusa', model:'Crestline', p:{b:0.9}, sizes:SZ.bcd, src:'szacunek'},
  {id:'tusa-boots-5', cat:'boots', brand:'Tusa', model:'Buty Imprex 5 mm (z zamkiem)', p:{t:5, cover:'boots', mass:900}, sizes:SZ.boot, src:'grubość: producent; masa: szacunek'},
  {id:'tusa-boots-3', cat:'boots', brand:'Tusa', model:'Buty Imprex Slipper 3 mm', p:{t:3, cover:'boots', mass:650}, sizes:SZ.boot, src:'grubość: producent; masa: szacunek'},
  {id:'tusa-gloves-3', cat:'gloves', brand:'Tusa', model:'Rękawice 3 mm', p:{t:3, cover:'gloves'}, sizes:SZ.glove, src:'szacunek'},
  // ===== Scubatech =====
  {id:'st-proterm2-77', cat:'wetsuit', brand:'Scubatech', model:'Proterm II 7 mm', p:{t:7, cover:'full'}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'st-proterm2-short', cat:'wetsuit', brand:'Scubatech', model:'Proterm II 7 mm krótka', p:{t:7, cover:'shorty'}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'st-proterm2-vest', cat:'over', brand:'Scubatech', model:'Proterm II docieplenie 7 mm z kapturem', p:{t:7, cover:'vest', hood:true}, sizes:SZ.suit, src:'szacunek (krój)'},
  {id:'st-vest-3', cat:'over', brand:'Scubatech', model:'Kamizelka neoprenowa 3 mm', p:{t:3, cover:'vest'}, sizes:SZ.suit, src:'producent (grubość)'},
  {id:'st-boots-5', cat:'boots', brand:'Scubatech', model:'Buty 5 mm', p:{t:5, cover:'boots', mass:800}, sizes:SZ.boot, src:'grubość: producent; masa: szacunek'},
  {id:'st-boots-komfort-5', cat:'boots', brand:'Scubatech', model:'Buty Komfort 5 mm', p:{t:5, cover:'boots', mass:900}, sizes:SZ.boot, src:'grubość: producent; masa: szacunek'},
  {id:'st-boots-titan-7', cat:'boots', brand:'Scubatech', model:'Buty Komfort Titanium 7 mm', p:{t:7, cover:'boots', mass:1050}, sizes:SZ.boot, src:'grubość: producent; masa: szacunek'},
  {id:'st-gloves-25', cat:'gloves', brand:'Scubatech', model:'Rękawice Super Stretch 2,5 mm', p:{t:2.5, cover:'gloves'}, sizes:SZ.glove, src:'producent (grubość)'},
  // ===== Buty innych marek =====
  {id:'mares-flexa-ds-5', cat:'boots', brand:'Mares', model:'Buty Flexa DS 5 mm', p:{t:5, cover:'boots', mass:950}, sizes:SZ.maresBoot, src:'grubość: producent; masa: szacunek'},
  {id:'mares-classic-5', cat:'boots', brand:'Mares', model:'Buty Classic NG 5 mm', p:{t:5, cover:'boots', mass:800}, sizes:SZ.maresBoot, src:'grubość: producent; masa: szacunek'},
  {id:'sp-delta-5', cat:'boots', brand:'Scubapro', model:'Buty Delta 5 mm', p:{t:5, cover:'boots', mass:1000}, sizes:SZ.boot, src:'grubość: producent; masa: szacunek'},
  {id:'sp-everflex-boots-5', cat:'boots', brand:'Scubapro', model:'Buty Everflex 5 mm', p:{t:5, cover:'boots', mass:900}, sizes:SZ.boot, src:'grubość: producent; masa: szacunek'},
  {id:'cressi-isla-5', cat:'boots', brand:'Cressi', model:'Buty Isla 5 mm', p:{t:5, cover:'boots', mass:800}, sizes:SZ.boot, src:'grubość: producent; masa: szacunek'},
  {id:'cressi-minorca-3', cat:'boots', brand:'Cressi', model:'Buty Minorca 3 mm', p:{t:3, cover:'boots', mass:600}, sizes:SZ.boot, src:'grubość: producent; masa: szacunek'},
  // ===== Płetwy (b = wyporność pary w wodzie, kg; mass = masa pary, g) =====
  {id:'fin-sp-jet', cat:'fins', brand:'Scubapro', model:'Jet Fin (guma)', p:{b:-0.7, mass:2400}, sizes:SZ.finJet, src:'szacunek z masy i materiału'},
  {id:'fin-sp-nova', cat:'fins', brand:'Scubapro', model:'Seawing Nova', p:{b:-0.1, mass:1500}, sizes:SZ.fin, src:'szacunek z masy i materiału'},
  {id:'fin-sp-gosport', cat:'fins', brand:'Scubapro', model:'Go Sport', p:{b:0.1, mass:1300}, sizes:SZ.fin, src:'szacunek z masy i materiału'},
  {id:'fin-sp-twinjet', cat:'fins', brand:'Scubapro', model:'Twin Jet Max', p:{b:-0.2, mass:1700}, sizes:SZ.fin, src:'szacunek z masy i materiału'},
  {id:'fin-mares-aq-plus', cat:'fins', brand:'Mares', model:'Avanti Quattro+', p:{b:-0.2, mass:1700}, sizes:SZ.maresFin, src:'szacunek z masy i materiału'},
  {id:'fin-mares-aq-power', cat:'fins', brand:'Mares', model:'Avanti Quattro Power', p:{b:-0.3, mass:1900}, sizes:SZ.maresFin, src:'szacunek z masy i materiału'},
  {id:'fin-mares-xstream', cat:'fins', brand:'Mares', model:'X-Stream', p:{b:-0.1, mass:1600}, sizes:SZ.maresFin, src:'szacunek z masy i materiału'},
  {id:'fin-mares-plana', cat:'fins', brand:'Mares', model:'Plana Avanti Tre', p:{b:-0.1, mass:1400}, sizes:SZ.maresFin, src:'szacunek z masy i materiału'},
  {id:'fin-cressi-frogplus', cat:'fins', brand:'Cressi', model:'Frog Plus', p:{b:-0.3, mass:1600}, sizes:SZ.fin, src:'szacunek z masy i materiału'},
  {id:'fin-cressi-prolight', cat:'fins', brand:'Cressi', model:'Pro Light', p:{b:-0.1, mass:1200}, sizes:SZ.fin, src:'szacunek z masy i materiału'},
  {id:'fin-cressi-reaction', cat:'fins', brand:'Cressi', model:'Reaction EBS', p:{b:-0.1, mass:1400}, sizes:SZ.fin, src:'szacunek z masy i materiału'},
  {id:'fin-tusa-solla', cat:'fins', brand:'Tusa', model:'Solla', p:{b:0.0, mass:1300}, sizes:SZ.fin, src:'szacunek z masy i materiału'},
  {id:'fin-tusa-hyflex', cat:'fins', brand:'Tusa', model:'Hyflex Switch', p:{b:0.0, mass:1400}, sizes:SZ.fin, src:'szacunek z masy i materiału'},
  {id:'fin-tusa-xpert', cat:'fins', brand:'Tusa', model:'X-Pert Zoom Z3', p:{b:-0.1, mass:1500}, sizes:SZ.fin, src:'szacunek z masy i materiału'},
  {id:'fin-al-storm', cat:'fins', brand:'Aqualung', model:'Storm', p:{b:-0.3, mass:1800}, sizes:SZ.fin, src:'szacunek z masy i materiału'},
  {id:'fin-al-phase', cat:'fins', brand:'Aqualung', model:'Phase', p:{b:0.0, mass:1300}, sizes:SZ.fin, src:'szacunek z masy i materiału'},
  {id:'fin-al-hotshot', cat:'fins', brand:'Aqualung', model:'Hotshot', p:{b:0.1, mass:1100}, sizes:SZ.fin, src:'szacunek z masy i materiału'},
  {id:'fin-apeks-rk3', cat:'fins', brand:'Apeks', model:'RK3 (guma)', p:{b:-0.6, mass:2200}, sizes:SZ.fin, src:'szacunek z masy i materiału'},
  {id:'fin-hollis-f1', cat:'fins', brand:'Hollis', model:'F1 (guma)', p:{b:-1.2, mass:3000}, sizes:SZ.finHollis, src:'szacunek z masy i materiału'},
  {id:'fin-hollis-f1lt', cat:'fins', brand:'Hollis', model:'F1 LT', p:{b:-0.5, mass:2000}, sizes:SZ.finHollis, src:'szacunek z masy i materiału'},
  {id:'fin-tecline-power', cat:'fins', brand:'Tecline', model:'Power Fins (guma)', p:{b:-0.6, mass:2300}, sizes:SZ.fin, src:'szacunek z masy i materiału'},
  {id:'fin-scubatech-tiara', cat:'fins', brand:'Scubatech', model:'Tiara Pro', p:{b:-0.2, mass:1500}, sizes:SZ.fin, src:'szacunek z masy i materiału'},
  {id:'fin-scubatech-xpower', cat:'fins', brand:'Scubatech', model:'XPower', p:{b:-0.1, mass:1300}, sizes:SZ.fin, src:'szacunek z masy i materiału'},
  {id:'misc-fins-rubber', cat:'fins', brand:'Ogólne', model:'Płetwy gumowe (np. Jet Fin)', p:{b:-0.7}, sizes:SZ.one, src:'szacunek'},
  {id:'misc-fins-plastic', cat:'fins', brand:'Ogólne', model:'Płetwy plastikowe', p:{b:0}, sizes:SZ.one, src:'szacunek'},
  // --- Drobne ---
  {id:'misc-reg', cat:'misc', brand:'Ogólne', model:'Automat + oktopus + manometr', p:{b:-0.9}, sizes:SZ.one, src:'szacunek'},
  {id:'misc-light', cat:'misc', brand:'Ogólne', model:'Latarka główna', p:{b:-0.3}, sizes:SZ.one, src:'szacunek'},
  {id:'misc-camera', cat:'misc', brand:'Ogólne', model:'Aparat w obudowie', p:{b:0.3}, sizes:SZ.one, src:'wpisz własną wartość'},
];

const CATS = {
  wetsuit:{label:'Pianki', one:'Pianka'},
  over:{label:'Ocieplacze mokre', one:'Ocieplacz'},
  hood:{label:'Kaptury', one:'Kaptur'},
  gloves:{label:'Rękawice', one:'Rękawice'},
  boots:{label:'Buty', one:'Buty'},
  dry:{label:'Suche skafandry', one:'Suchy skafander'},
  under:{label:'Ocieplacze do suchego', one:'Ocieplacz do suchego'},
  bcd:{label:'Kamizelki', one:'Kamizelka'},
  wing:{label:'Skrzydła', one:'Skrzydło'},
  tank:{label:'Butle', one:'Butla'},
  stage:{label:'Butle stage', one:'Butla stage'},
  fins:{label:'Płetwy', one:'Płetwy'},
  misc:{label:'Drobne', one:'Drobne'}
};
const CAT_ORDER = ['wetsuit','over','hood','gloves','boots','dry','under','bcd','wing','tank','stage','fins','misc'];

// ===== Akweny: temperatury orientacyjne [sty..gru] =====
// Akwen opisuje lista nurkowisk: [szerokość, długość, promień w km]. Promień jest na punkt, bo
// zatoka bywa rozległa, a kamieniołom ma kilkaset metrów; `r` akwenu to tylko wartość domyślna.
// Liczby punktów nie ograniczamy — im dokładniejsza lista, tym uczciwsze dopasowanie pozycji.
// Współrzędne są przybliżone (~1 km): mają wskazać właściwy akwen, nie wejście do wody.
const SITE_PRESETS = [
  {id:'marsaalam', name:'Marsa Alam', lat:25.07, lon:34.89, r:10, rho:1.029,
   pts:[[25.07,34.89,10],[25.24,34.80,8],[25.35,34.77,8],[25.53,34.64,8],[24.86,35.03,8],[25.87,34.40,10],[24.38,35.45,12],[24.28,35.47,12],[25.62,34.60,8]],
   ts:[23,22,22,23,25,27,28,29,28,27,26,24], tb:[22,21,21,22,24,26,27,28,27,26,25,23]},
  {id:'dahab', name:'Dahab', lat:28.50, lon:34.51, r:4, rho:1.029,
   pts:[[28.50,34.51,4],[28.57,34.54,3],[28.52,34.53,3],[28.61,34.52,3],[28.48,34.52,3],[28.54,34.53,3]],
   ts:[21,21,21,22,24,26,28,29,28,26,24,22], tb:[21,20,20,21,23,25,27,28,27,25,23,22]},
  {id:'redsea', name:'Morze Czerwone (inne)', lat:27.25, lon:33.81, r:20, rho:1.029,
   pts:[[27.25,33.81,25],[27.40,33.68,15],[26.75,33.94,20],[26.10,34.28,20],[27.86,34.30,25],[27.73,34.25,15],[28.98,34.67,15],[29.50,34.90,15],[27.90,34.32,12],[26.55,34.00,15],[25.95,34.35,12]],
   ts:[23,22,22,23,25,27,28,29,28,27,26,24], tb:[22,21,21,22,24,26,27,28,27,26,25,23]},
  {id:'malta', name:'Malta', lat:35.89, lon:14.45, r:5, rho:1.028,
   pts:[[35.99,14.33,5],[35.92,14.48,4],[35.89,14.45,5],[35.83,14.45,5],[35.86,14.57,5],[35.93,14.34,4],[35.95,14.41,4],[35.81,14.54,5],[35.90,14.51,4]],
   ts:[15,15,15,16,19,22,25,26,25,23,20,17], tb:[15,14,14,15,16,17,18,19,20,21,19,16]},
  {id:'gozo', name:'Gozo, Comino', lat:36.04, lon:14.25, r:4, rho:1.028,
   pts:[[36.05,14.19,4],[36.03,14.21,4],[36.07,14.26,4],[36.04,14.25,4],[36.02,14.30,3],[36.01,14.33,4],[36.00,14.34,3]],
   ts:[15,15,15,16,19,22,25,26,25,23,20,17], tb:[15,14,14,15,16,17,18,19,20,21,19,16]},
  {id:'croatia', name:'Chorwacja (Adriatyk)', lat:44.87, lon:13.85, r:20, rho:1.028,
   pts:[[44.87,13.85,20],[45.08,13.64,15],[45.03,14.58,20],[44.75,14.76,20],[44.55,14.40,15],[44.12,15.23,20],[43.74,15.89,20],[43.51,16.44,20],[43.17,16.44,20],[43.05,16.15,15],[42.96,17.14,20],[42.65,18.09,20],[42.79,17.55,15]],
   ts:[13,13,13,15,18,22,24,25,23,20,17,15], tb:[13,13,13,13,14,15,16,17,18,18,16,14]},
  {id:'cyprus', name:'Cypr', lat:34.92, lon:33.64, r:12, rho:1.028,
   pts:[[34.92,33.64,12],[34.88,33.63,10],[34.68,33.04,12],[34.75,32.42,12],[34.99,34.00,10],[35.04,34.05,10],[34.55,32.97,10],[35.16,33.95,10]],
   ts:[17,17,17,18,21,24,27,28,27,25,22,19], tb:[17,16,16,17,18,20,22,24,24,23,21,18]},
  {id:'baltic', name:'Bałtyk', lat:54.60, lon:18.80, r:15, rho:1.005,
   pts:[[54.60,18.80,15],[54.53,18.55,12],[54.60,18.35,12],[54.79,18.40,12],[54.75,18.55,10],[54.68,18.80,12],[54.38,18.66,12],[54.58,16.87,12],[54.47,16.20,12],[54.42,16.55,10],[54.19,15.58,12],[54.03,14.75,12],[53.92,14.25,15],[54.83,18.20,20]],
   ts:[3,2,3,5,9,14,17,18,15,11,7,4], tb:[4,4,4,4,5,6,7,8,8,8,7,5]},
  {id:'hancza', name:'Hańcza', lat:54.27, lon:22.82, r:4, rho:1.000,
   ts:[3,3,4,7,13,18,21,21,17,12,7,4], tb:[4,4,4,4,5,5,5,5,5,5,5,4]},
  {id:'koparki', name:'Koparki (Jaworzno)', lat:50.19, lon:19.31, r:4, rho:1.000,
   ts:[4,4,4,6,12,18,21,21,17,12,7,4], tb:[4,4,4,5,6,7,8,8,8,7,6,4]},
  {id:'piechcin', name:'Piechcin (kamieniołom)', lat:52.98, lon:18.0, r:4, rho:1.000,
   ts:[3,3,4,8,14,19,22,22,18,12,7,4], tb:[4,4,4,5,6,7,8,8,8,7,6,4]},
  {id:'honoratka', name:'Honoratka', lat:52.327, lon:18.277, r:4, rho:1.000,
   ts:[3,3,4,8,14,19,22,22,18,12,7,4], tb:[4,4,4,6,10,14,16,17,15,11,7,5]},
  {id:'deepspot', name:'Deepspot (basen)', lat:51.97, lon:20.51, r:3, rho:1.000,
   ts:[33,33,33,33,33,33,33,33,33,33,33,33], tb:[32,32,32,32,32,32,32,32,32,32,32,32]}
];
const WATER_TYPES = [
  {rho:1.029, label:'Morze Czerwone · 40‰'},
  {rho:1.028, label:'Morze Śródziemne · 38‰'},
  {rho:1.025, label:'Ocean · 35‰'},
  {rho:1.005, label:'Bałtyk · 7‰'},
  {rho:1.000, label:'Woda słodka'}
];
