// ===== Katalog sprzętu =====
// Wartości pływalności: "szacunek" = wyliczone z fizyki / typowych danych, nie z pomiaru producenta.
const SZ = {
  mares: ['1','2','3','4','5','6','7','8'],
  cressi: ['XS/1','S/2','M/3','L/4','XL/5','XXL/6','XXXL/7'],
  scubapro: ['XS','S','M','L','XL','XXL','3XL'],
  fe: ['S','MS','M','ML','L','LT','XL','XXL'],
  santi: ['S','M','ML','L','LT','XL','XXL','MTF'],
  avatar: ['S','M','L','XL','XXL','na miarę'],
  harness: ['S','M','L','XL','uniwersalny'],
  one: ['uniwersalny']
};
const CATALOG = [
  // --- Pianki mokre i półsuche ---
  {id:'mares-reef-3', cat:'wetsuit', brand:'Mares', model:'Reef 3 mm', p:{t:3, cover:'full'}, sizes:SZ.mares, src:'producent (grubość)'},
  {id:'mares-flexa-543', cat:'wetsuit', brand:'Mares', model:'Flexa 5.4.3', p:{t:5, tl:4, cover:'full'}, sizes:SZ.mares, src:'producent (grubość)'},
  {id:'mares-flexa-865', cat:'wetsuit', brand:'Mares', model:'Flexa 8.6.5', p:{t:8, tl:6, cover:'full'}, sizes:SZ.mares, src:'producent (grubość)'},
  {id:'mares-evo-5', cat:'wetsuit', brand:'Mares', model:'Evolution 5 mm', p:{t:5, cover:'full'}, sizes:SZ.mares, src:'producent (grubość)'},
  {id:'mares-evo-7', cat:'wetsuit', brand:'Mares', model:'Evolution 7 mm', p:{t:7, cover:'full'}, sizes:SZ.mares, src:'producent (grubość)'},
  {id:'mares-protherm-87', cat:'wetsuit', brand:'Mares', model:'Pro Therm 8/7 półsucha, kaptur', p:{t:8, tl:7, cover:'full', semi:true, hood:true}, sizes:SZ.mares, src:'producent (grubość)'},
  {id:'cressi-morea-3', cat:'wetsuit', brand:'Cressi', model:'Morea 3 mm', p:{t:3, cover:'full'}, sizes:SZ.cressi, src:'producent (grubość)'},
  {id:'cressi-fast-5', cat:'wetsuit', brand:'Cressi', model:'Fast 5 mm', p:{t:5, cover:'full'}, sizes:SZ.cressi, src:'producent (grubość)'},
  {id:'cressi-fast-7', cat:'wetsuit', brand:'Cressi', model:'Fast 7 mm', p:{t:7, cover:'full'}, sizes:SZ.cressi, src:'producent (grubość)'},
  {id:'cressi-castoro-7', cat:'wetsuit', brand:'Cressi', model:'Castoro 7 mm (dwuczęściowa)', p:{t:7, cover:'full'}, sizes:SZ.cressi, src:'producent (grubość)'},
  {id:'cressi-lontra-7', cat:'wetsuit', brand:'Cressi', model:'Lontra 7 mm półsucha', p:{t:7, cover:'full', semi:true, hood:true}, sizes:SZ.cressi, src:'producent (grubość)'},
  {id:'sp-def-3', cat:'wetsuit', brand:'Scubapro', model:'Definition 3 mm', p:{t:3, cover:'full'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'sp-def-5', cat:'wetsuit', brand:'Scubapro', model:'Definition 5 mm', p:{t:5, cover:'full'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'sp-def-65', cat:'wetsuit', brand:'Scubapro', model:'Definition 6.5 mm', p:{t:6.5, cover:'full'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'sp-everflex-32', cat:'wetsuit', brand:'Scubapro', model:'Everflex YULEX 3/2', p:{t:3, tl:2, cover:'full'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'sp-everflex-54', cat:'wetsuit', brand:'Scubapro', model:'Everflex YULEX 5/4', p:{t:5, tl:4, cover:'full'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'sp-everflex-75', cat:'wetsuit', brand:'Scubapro', model:'Everflex YULEX 7/5', p:{t:7, tl:5, cover:'full'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'sp-novascotia-75', cat:'wetsuit', brand:'Scubapro', model:'Novascotia 7.5 półsucha', p:{t:7.5, cover:'full', semi:true, hood:true}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'fe-proteus-3', cat:'wetsuit', brand:'Fourth Element', model:'Proteus II 3 mm', p:{t:3, cover:'full'}, sizes:SZ.fe, src:'producent (grubość)'},
  {id:'fe-proteus-5', cat:'wetsuit', brand:'Fourth Element', model:'Proteus II 5 mm', p:{t:5, cover:'full'}, sizes:SZ.fe, src:'producent (grubość)'},
  {id:'fe-proteus-7', cat:'wetsuit', brand:'Fourth Element', model:'Proteus II 7 mm', p:{t:7, cover:'full'}, sizes:SZ.fe, src:'producent (grubość)'},
  {id:'gen-shorty-3', cat:'wetsuit', brand:'Ogólne', model:'Shorty 3 mm', p:{t:3, cover:'shorty'}, sizes:SZ.one, src:'szacunek'},
  {id:'gen-longjohn-5', cat:'wetsuit', brand:'Ogólne', model:'Long john 5 mm', p:{t:5, cover:'longjohn'}, sizes:SZ.one, src:'szacunek'},
  // --- Ocieplacze mokre ---
  {id:'mares-flexacore', cat:'over', brand:'Mares', model:'Flexa Core 3/4 z kapturem', p:{t:3, cover:'overhood', hood:true}, sizes:SZ.mares, src:'szacunek (grubość do sprawdzenia)'},
  {id:'gen-vest-hood-3', cat:'over', brand:'Ogólne', model:'Kamizelka z kapturem 3 mm', p:{t:3, cover:'vest', hood:true}, sizes:SZ.one, src:'szacunek'},
  {id:'gen-vest-hood-5', cat:'over', brand:'Ogólne', model:'Kamizelka z kapturem 5 mm', p:{t:5, cover:'vest', hood:true}, sizes:SZ.one, src:'szacunek'},
  {id:'gen-shorty-over-2', cat:'over', brand:'Ogólne', model:'Shorty ocieplacz 2 mm', p:{t:2, cover:'shorty'}, sizes:SZ.one, src:'szacunek'},
  // --- Kaptury, rękawice, buty ---
  {id:'gen-hood-3', cat:'hood', brand:'Ogólne', model:'Kaptur 3 mm', p:{t:3, cover:'hood', hood:true}, sizes:SZ.one, src:'szacunek'},
  {id:'gen-hood-5', cat:'hood', brand:'Ogólne', model:'Kaptur 5 mm', p:{t:5, cover:'hood', hood:true}, sizes:SZ.one, src:'szacunek'},
  {id:'gen-hood-7', cat:'hood', brand:'Ogólne', model:'Kaptur 7 mm', p:{t:7, cover:'hood', hood:true}, sizes:SZ.one, src:'szacunek'},
  {id:'gen-gloves-3', cat:'gloves', brand:'Ogólne', model:'Rękawice 3 mm', p:{t:3, cover:'gloves'}, sizes:SZ.one, src:'szacunek'},
  {id:'gen-gloves-5', cat:'gloves', brand:'Ogólne', model:'Rękawice 5 mm', p:{t:5, cover:'gloves'}, sizes:SZ.one, src:'szacunek'},
  {id:'mares-flexa-boots-5', cat:'boots', brand:'Mares', model:'Buty Flexa 5 mm', p:{t:5, cover:'boots'}, sizes:SZ.mares, src:'producent (grubość)'},
  {id:'gen-boots-3', cat:'boots', brand:'Ogólne', model:'Buty 3 mm', p:{t:3, cover:'boots'}, sizes:SZ.one, src:'szacunek'},
  {id:'gen-boots-7', cat:'boots', brand:'Ogólne', model:'Buty 7 mm', p:{t:7, cover:'boots'}, sizes:SZ.one, src:'szacunek'},
  // --- Suche skafandry ---
  {id:'santi-elite', cat:'dry', brand:'Santi', model:'E.Lite+ (trylaminat)', p:{shell:'trilam', b:0.3}, sizes:SZ.santi, src:'szacunek'},
  {id:'santi-emotion', cat:'dry', brand:'Santi', model:'E.Motion+ (trylaminat)', p:{shell:'trilam', b:0.3}, sizes:SZ.santi, src:'szacunek'},
  {id:'avatar-101', cat:'dry', brand:'Avatar', model:'101 (membrana 4-warstwowa)', p:{shell:'membrane', b:0.4}, sizes:SZ.avatar, src:'szacunek'},
  {id:'avatar-102', cat:'dry', brand:'Avatar', model:'102 Airon (trylaminat)', p:{shell:'trilam', b:0.3}, sizes:SZ.avatar, src:'szacunek'},
  {id:'sp-evertech', cat:'dry', brand:'Scubapro', model:'Evertech Dry Breathable', p:{shell:'membrane', b:0.4}, sizes:SZ.scubapro, src:'szacunek'},
  {id:'sp-everdry4', cat:'dry', brand:'Scubapro', model:'Everdry 4 (neopren 4 mm)', p:{shell:'neo', t:4}, sizes:SZ.scubapro, src:'szacunek'},
  {id:'bare-aquatrek', cat:'dry', brand:'Bare', model:'Aqua Trek 1 (trylaminat)', p:{shell:'trilam', b:0.3}, sizes:SZ.scubapro, src:'szacunek'},
  {id:'gen-crushed', cat:'dry', brand:'Ogólne', model:'Neopren zgnieciony', p:{shell:'crushed', b:1.5}, sizes:SZ.one, src:'szacunek'},
  // --- Ocieplacze do suchego ---
  {id:'santi-flex80', cat:'under', brand:'Santi', model:'Flex 80', p:{g:2, tmin:14}, sizes:SZ.santi, src:'szacunek; zakres temp. orientacyjny'},
  {id:'santi-flex190', cat:'under', brand:'Santi', model:'Flex 190', p:{g:4, tmin:7}, sizes:SZ.santi, src:'szacunek; 7–14 °C wg sklepów'},
  {id:'santi-bz200', cat:'under', brand:'Santi', model:'BZ200', p:{g:5, tmin:5}, sizes:SZ.santi, src:'szacunek'},
  {id:'santi-bz400x', cat:'under', brand:'Santi', model:'BZ400X', p:{g:7, tmin:2}, sizes:SZ.santi, src:'szacunek; <7 °C wg sklepów'},
  {id:'avatar-901', cat:'under', brand:'Avatar', model:'901', p:{g:4, tmin:8}, sizes:SZ.avatar, src:'szacunek'},
  {id:'avatar-902', cat:'under', brand:'Avatar', model:'902', p:{g:6, tmin:4}, sizes:SZ.avatar, src:'szacunek'},
  {id:'fe-arctic', cat:'under', brand:'Fourth Element', model:'Arctic (góra + dół)', p:{g:5, tmin:5}, sizes:SZ.fe, src:'szacunek'},
  // --- Kamizelki (jacket, hybryda) ---
  {id:'mares-quantum', cat:'bcd', brand:'Mares', model:'Quantum', p:{b:1.2}, sizes:['XS','S','M','L','XL','XXL'], src:'szacunek'},
  {id:'mares-prestige', cat:'bcd', brand:'Mares', model:'Prestige', p:{b:1.0}, sizes:['XS','S','M','L','XL','XXL'], src:'szacunek'},
  {id:'mares-bolt', cat:'bcd', brand:'Mares', model:'Bolt SLS', p:{b:0.8}, sizes:['XS','S','M','L','XL','XXL'], src:'szacunek'},
  {id:'sp-hydros', cat:'bcd', brand:'Scubapro', model:'Hydros Pro', p:{b:0.5}, sizes:SZ.scubapro, src:'szacunek'},
  {id:'sp-knighthawk', cat:'bcd', brand:'Scubapro', model:'Knighthawk', p:{b:0.8}, sizes:SZ.scubapro, src:'szacunek'},
  {id:'sp-level', cat:'bcd', brand:'Scubapro', model:'Level', p:{b:1.0}, sizes:SZ.scubapro, src:'szacunek'},
  {id:'sp-go', cat:'bcd', brand:'Scubapro', model:'Go (podróżny)', p:{b:0.6}, sizes:SZ.scubapro, src:'szacunek'},
  {id:'cressi-aquaride', cat:'bcd', brand:'Cressi', model:'Aquaride', p:{b:1.0}, sizes:SZ.cressi, src:'szacunek'},
  {id:'cressi-travelight', cat:'bcd', brand:'Cressi', model:'Travelight', p:{b:0.6}, sizes:SZ.cressi, src:'szacunek'},
  {id:'cressi-start', cat:'bcd', brand:'Cressi', model:'Start', p:{b:1.0}, sizes:SZ.cressi, src:'szacunek'},
  {id:'gen-rental-jacket', cat:'bcd', brand:'Ogólne', model:'Jacket z wypożyczalni', p:{b:1.0}, sizes:SZ.one, src:'szacunek'},
  // --- Skrzydła z płytą ---
  {id:'xdeep-zeos28', cat:'wing', brand:'XDEEP', model:'Zeos 28 (13 kg)', p:{lift:13, plate:'alu'}, sizes:SZ.harness, src:'udźwig: producent; płyta: stal 2,06 kg / alu ~0,8 kg'},
  {id:'xdeep-zeos38', cat:'wing', brand:'XDEEP', model:'Zeos 38 (17 kg)', p:{lift:17, plate:'alu'}, sizes:SZ.harness, src:'udźwig: producent; płyta: stal 2,06 kg / alu ~0,8 kg'},
  {id:'xdeep-zen', cat:'wing', brand:'XDEEP', model:'Zen', p:{lift:15, plate:'soft'}, sizes:SZ.harness, src:'szacunek'},
  {id:'xdeep-ghost', cat:'wing', brand:'XDEEP', model:'Ghost', p:{lift:13, plate:'soft'}, sizes:SZ.harness, src:'szacunek'},
  {id:'tecline-peanut21', cat:'wing', brand:'Tecline', model:'Peanut 21', p:{lift:21, plate:'alu'}, sizes:SZ.harness, src:'szacunek'},
  {id:'tecline-peanut28', cat:'wing', brand:'Tecline', model:'Peanut 28', p:{lift:28, plate:'steel'}, sizes:SZ.harness, src:'szacunek'},
  {id:'mares-xr-trim', cat:'wing', brand:'Mares', model:'XR-Rec Trim', p:{lift:16, plate:'soft'}, sizes:SZ.harness, src:'szacunek'},
  {id:'mares-xr-hv', cat:'wing', brand:'Mares', model:'XR HV Single', p:{lift:16, plate:'alu'}, sizes:SZ.harness, src:'szacunek'},
  {id:'mares-xr-ice', cat:'wing', brand:'Mares', model:'XR-Rec Ice Single', p:{lift:16, plate:'steel'}, sizes:SZ.harness, src:'szacunek'},
  // --- Butle (be = wyporność pusta z zaworem w morzu 1,025; vd = objętość wypierana) ---
  {id:'st-10-232', cat:'tank', brand:'Stal', model:'10 l / 232 bar', p:{vol:10, bar:232, mat:'stal', be:-1.0, vd:11.7}, sizes:SZ.one, src:'szacunek (typowe butle EU)'},
  {id:'st-12-232', cat:'tank', brand:'Stal', model:'12 l / 232 bar', p:{vol:12, bar:232, mat:'stal', be:-1.4, vd:13.8}, sizes:SZ.one, src:'szacunek (typowe butle EU)'},
  {id:'st-12-300', cat:'tank', brand:'Stal', model:'12 l / 300 bar', p:{vol:12, bar:300, mat:'stal', be:-2.9, vd:14.3}, sizes:SZ.one, src:'szacunek (typowe butle EU)'},
  {id:'st-15-232', cat:'tank', brand:'Stal', model:'15 l / 232 bar', p:{vol:15, bar:232, mat:'stal', be:-1.6, vd:17.3}, sizes:SZ.one, src:'szacunek (typowe butle EU)'},
  {id:'al-s80', cat:'tank', brand:'Aluminium', model:'S80 11,1 l / 207 bar', p:{vol:11.1, bar:207, mat:'alu', be:1.8, vd:15.7}, sizes:SZ.one, src:'wypiera ~15,6 l, masa ~14,3 kg'},
  {id:'al-s100', cat:'tank', brand:'Aluminium', model:'S100 13,2 l / 232 bar', p:{vol:13.2, bar:232, mat:'alu', be:1.4, vd:18.5}, sizes:SZ.one, src:'szacunek'},
  {id:'al-15', cat:'tank', brand:'Aluminium', model:'15 l / 200 bar', p:{vol:15, bar:200, mat:'alu', be:2.2, vd:20.5}, sizes:SZ.one, src:'szacunek'},

  {id:'mares-flexa-hood-65', cat:'hood', brand:'Mares', model:'Kaptur Flexa 6.5 mm', p:{t:6.5, cover:'hood', hood:true}, sizes:SZ.mares, src:'producent (grubość)'},
  {id:'mares-flexa-gloves-5', cat:'gloves', brand:'Mares', model:'Rękawice Flexa Fit 5 mm', p:{t:5, cover:'gloves'}, sizes:SZ.mares, src:'producent (grubość)'},
  {id:'sp-everflex-hood-5', cat:'hood', brand:'Scubapro', model:'Kaptur Everflex 5/3 mm', p:{t:5, cover:'hood', hood:true}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'sp-everflex-gloves-5', cat:'gloves', brand:'Scubapro', model:'Rękawice Everflex 5 mm', p:{t:5, cover:'gloves'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'cressi-hood-5', cat:'hood', brand:'Cressi', model:'Kaptur 5 mm', p:{t:5, cover:'hood', hood:true}, sizes:SZ.cressi, src:'producent (grubość)'},
  {id:'cressi-gloves-5', cat:'gloves', brand:'Cressi', model:'Rękawice High Stretch 5 mm', p:{t:5, cover:'gloves'}, sizes:SZ.cressi, src:'producent (grubość)'},
  // ===== Bare =====
  {id:'bare-velocity-3', cat:'wetsuit', brand:'Bare', model:'Velocity Ultra 3 mm', p:{t:3, cover:'full'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'bare-velocity-5', cat:'wetsuit', brand:'Bare', model:'Velocity Ultra 5 mm', p:{t:5, cover:'full'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'bare-velocity-7', cat:'wetsuit', brand:'Bare', model:'Velocity Ultra 7 mm', p:{t:7, cover:'full'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'bare-reactive-5', cat:'wetsuit', brand:'Bare', model:'Reactive 5 mm', p:{t:5, cover:'full'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'bare-velocity-semi-7', cat:'wetsuit', brand:'Bare', model:'Velocity Semi-Dry 7 mm, kaptur', p:{t:7, cover:'full', semi:true, hood:true}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'bare-uw-hood-7', cat:'hood', brand:'Bare', model:'Ultrawarmth kaptur 7 mm', p:{t:7, cover:'hood', hood:true}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'bare-uw-gloves-5', cat:'gloves', brand:'Bare', model:'Ultrawarmth rękawice 5 mm', p:{t:5, cover:'gloves'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'bare-uw-boots-7', cat:'boots', brand:'Bare', model:'Ultrawarmth buty 7 mm', p:{t:7, cover:'boots', mass:1100}, sizes:['36','38','40','42','44','46','48'], src:'grubość: producent; masa: szacunek'},
  {id:'bare-velocity-boots-5', cat:'boots', brand:'Bare', model:'Velocity buty 5 mm', p:{t:5, cover:'boots', mass:900}, sizes:['36','38','40','42','44','46','48'], src:'grubość: producent; masa: szacunek'},
  {id:'bare-xmission', cat:'dry', brand:'Bare', model:'X-Mission Evolution (trylaminat)', p:{shell:'trilam', b:0.3}, sizes:SZ.scubapro, src:'szacunek'},
  {id:'bare-expedition-hd2', cat:'dry', brand:'Bare', model:'Expedition HD2 (trylaminat)', p:{shell:'trilam', b:0.4}, sizes:SZ.scubapro, src:'szacunek'},
  {id:'bare-sb-mid', cat:'under', brand:'Bare', model:'SB System Mid Layer', p:{g:4, tmin:7}, sizes:SZ.scubapro, src:'szacunek'},
  {id:'bare-uw-base', cat:'under', brand:'Bare', model:'Ultrawarmth Base Layer', p:{g:2, tmin:13}, sizes:SZ.scubapro, src:'szacunek'},
  // ===== Aqualung =====
  {id:'al-dynaflex-3', cat:'wetsuit', brand:'Aqualung', model:'Dynaflex 3 mm', p:{t:3, cover:'full'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'al-dynaflex-55', cat:'wetsuit', brand:'Aqualung', model:'Dynaflex 5.5 mm', p:{t:5.5, cover:'full'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'al-dynaflex-7', cat:'wetsuit', brand:'Aqualung', model:'Dynaflex 7 mm', p:{t:7, cover:'full'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'al-hydroflex-3', cat:'wetsuit', brand:'Aqualung', model:'HydroFlex 3 mm', p:{t:3, cover:'full'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'al-hydroflex-5', cat:'wetsuit', brand:'Aqualung', model:'HydroFlex 5 mm', p:{t:5, cover:'full'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'al-solafx-8', cat:'wetsuit', brand:'Aqualung', model:'SolAfx 8/7 półsucha, kaptur', p:{t:8, tl:7, cover:'full', semi:true, hood:true}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'al-superzip-5', cat:'boots', brand:'Aqualung', model:'Superzip Ergo buty 5 mm', p:{t:5, cover:'boots', mass:1000}, sizes:['36','38','40','42','44','46','48'], src:'grubość: producent; masa: szacunek'},
  {id:'al-echozip-5', cat:'boots', brand:'Aqualung', model:'Echozip buty 5 mm', p:{t:5, cover:'boots', mass:850}, sizes:['36','38','40','42','44','46','48'], src:'grubość: producent; masa: szacunek'},
  {id:'al-gloves-5', cat:'gloves', brand:'Aqualung', model:'Superstretch rękawice 5 mm', p:{t:5, cover:'gloves'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'al-hood-5', cat:'hood', brand:'Aqualung', model:'Kaptur 5/3 mm', p:{t:5, cover:'hood', hood:true}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'al-blizzard', cat:'dry', brand:'Aqualung', model:'Blizzard Pro (neopren 4 mm)', p:{shell:'neo', t:4}, sizes:SZ.scubapro, src:'szacunek'},
  {id:'al-fusion', cat:'dry', brand:'Aqualung', model:'Fusion Sport (membrana)', p:{shell:'membrane', b:0.8}, sizes:SZ.scubapro, src:'szacunek'},
  {id:'al-prohd', cat:'bcd', brand:'Aqualung', model:'Pro HD', p:{b:1.2}, sizes:SZ.scubapro, src:'szacunek'},
  {id:'al-axiom', cat:'bcd', brand:'Aqualung', model:'Axiom', p:{b:1.0}, sizes:SZ.scubapro, src:'szacunek'},
  {id:'al-rogue', cat:'bcd', brand:'Aqualung', model:'Rogue', p:{b:0.8}, sizes:SZ.scubapro, src:'szacunek'},
  {id:'al-wave', cat:'bcd', brand:'Aqualung', model:'Wave', p:{b:0.9}, sizes:SZ.scubapro, src:'szacunek'},
  {id:'al-zuma', cat:'bcd', brand:'Aqualung', model:'Zuma (podróżny)', p:{b:0.5}, sizes:SZ.scubapro, src:'szacunek'},
  {id:'al-outlaw', cat:'bcd', brand:'Aqualung', model:'Outlaw', p:{b:0.6}, sizes:SZ.scubapro, src:'szacunek'},
  // ===== Tusa =====
  {id:'tusa-liberator', cat:'bcd', brand:'Tusa', model:'Liberator Sigma II', p:{b:1.0}, sizes:SZ.scubapro, src:'szacunek'},
  {id:'tusa-libero', cat:'bcd', brand:'Tusa', model:'Libero II', p:{b:0.9}, sizes:SZ.scubapro, src:'szacunek'},
  {id:'tusa-boots-5', cat:'boots', brand:'Tusa', model:'Buty z zamkiem 5 mm', p:{t:5, cover:'boots', mass:900}, sizes:['36','38','40','42','44','46'], src:'grubość: producent; masa: szacunek'},
  {id:'tusa-boots-3', cat:'boots', brand:'Tusa', model:'Buty 3 mm', p:{t:3, cover:'boots', mass:650}, sizes:['36','38','40','42','44','46'], src:'grubość: producent; masa: szacunek'},
  {id:'tusa-gloves-3', cat:'gloves', brand:'Tusa', model:'Rękawice 3 mm', p:{t:3, cover:'gloves'}, sizes:SZ.scubapro, src:'szacunek'},
  // ===== Scubatech =====
  {id:'st-proterm2-77', cat:'wetsuit', brand:'Scubatech', model:'Proterm II 7 mm', p:{t:7, cover:'full'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'st-proterm2-short', cat:'wetsuit', brand:'Scubatech', model:'Proterm II 7 mm krótka', p:{t:7, cover:'shorty'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'st-proterm2-vest', cat:'over', brand:'Scubatech', model:'Proterm II docieplenie 7 mm z kapturem', p:{t:7, cover:'vest', hood:true}, sizes:SZ.scubapro, src:'szacunek (krój)'},
  {id:'st-vest-3', cat:'over', brand:'Scubatech', model:'Kamizelka neoprenowa 3 mm', p:{t:3, cover:'vest'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  {id:'st-boots-5', cat:'boots', brand:'Scubatech', model:'Buty 5 mm', p:{t:5, cover:'boots', mass:800}, sizes:['36','38','40','42','44','46','48'], src:'grubość: producent; masa: szacunek'},
  {id:'st-boots-komfort-5', cat:'boots', brand:'Scubatech', model:'Buty Komfort 5 mm', p:{t:5, cover:'boots', mass:900}, sizes:['36','38','40','42','44','46','48'], src:'grubość: producent; masa: szacunek'},
  {id:'st-boots-titan-7', cat:'boots', brand:'Scubatech', model:'Buty Komfort Titanium 7 mm', p:{t:7, cover:'boots', mass:1050}, sizes:['36','38','40','42','44','46','48'], src:'grubość: producent; masa: szacunek'},
  {id:'st-gloves-25', cat:'gloves', brand:'Scubatech', model:'Rękawice Super Stretch 2,5 mm', p:{t:2.5, cover:'gloves'}, sizes:SZ.scubapro, src:'producent (grubość)'},
  // ===== Buty innych marek =====
  {id:'mares-flexa-ds-5', cat:'boots', brand:'Mares', model:'Buty Flexa DS 5 mm', p:{t:5, cover:'boots', mass:950}, sizes:SZ.mares, src:'grubość: producent; masa: szacunek'},
  {id:'mares-classic-5', cat:'boots', brand:'Mares', model:'Buty Classic NG 5 mm', p:{t:5, cover:'boots', mass:800}, sizes:SZ.mares, src:'grubość: producent; masa: szacunek'},
  {id:'sp-delta-5', cat:'boots', brand:'Scubapro', model:'Buty Delta 5 mm', p:{t:5, cover:'boots', mass:1000}, sizes:['36','38','40','42','44','46','48'], src:'grubość: producent; masa: szacunek'},
  {id:'sp-everflex-boots-5', cat:'boots', brand:'Scubapro', model:'Buty Everflex 5 mm', p:{t:5, cover:'boots', mass:900}, sizes:['36','38','40','42','44','46','48'], src:'grubość: producent; masa: szacunek'},
  {id:'cressi-isla-5', cat:'boots', brand:'Cressi', model:'Buty Isla 5 mm', p:{t:5, cover:'boots', mass:800}, sizes:['36','38','40','42','44','46','48'], src:'grubość: producent; masa: szacunek'},
  {id:'cressi-minorca-3', cat:'boots', brand:'Cressi', model:'Buty Minorca 3 mm', p:{t:3, cover:'boots', mass:600}, sizes:['36','38','40','42','44','46','48'], src:'grubość: producent; masa: szacunek'},
  // ===== Płetwy (b = wyporność pary w wodzie, kg; mass = masa pary, g) =====
  {id:'fin-sp-jet', cat:'fins', brand:'Scubapro', model:'Jet Fin (guma)', p:{b:-0.7, mass:2400, mat:'guma'}, sizes:['S','M','L','XL','XXL'], src:'szacunek z masy i materiału'},
  {id:'fin-sp-nova', cat:'fins', brand:'Scubapro', model:'Seawing Nova', p:{b:-0.1, mass:1500, mat:'Monprene'}, sizes:['XS','S','M','L','XL'], src:'szacunek z masy i materiału'},
  {id:'fin-sp-gosport', cat:'fins', brand:'Scubapro', model:'Go Sport', p:{b:0.1, mass:1300, mat:'Monprene'}, sizes:['XS','S','M','L','XL'], src:'szacunek z masy i materiału'},
  {id:'fin-sp-twinjet', cat:'fins', brand:'Scubapro', model:'Twin Jet Max', p:{b:-0.2, mass:1700, mat:'Monprene'}, sizes:['S','M','L','XL'], src:'szacunek z masy i materiału'},
  {id:'fin-mares-aq-plus', cat:'fins', brand:'Mares', model:'Avanti Quattro+', p:{b:-0.2, mass:1700, mat:'Tecralene'}, sizes:['XS','S','M','L','XL'], src:'szacunek z masy i materiału'},
  {id:'fin-mares-aq-power', cat:'fins', brand:'Mares', model:'Avanti Quattro Power', p:{b:-0.3, mass:1900, mat:'Tecralene'}, sizes:['XS','S','M','L','XL'], src:'szacunek z masy i materiału'},
  {id:'fin-mares-xstream', cat:'fins', brand:'Mares', model:'X-Stream', p:{b:-0.1, mass:1600, mat:'Tecralene'}, sizes:['XS','S','M','L','XL'], src:'szacunek z masy i materiału'},
  {id:'fin-mares-plana', cat:'fins', brand:'Mares', model:'Plana Avanti Tre', p:{b:-0.1, mass:1400, mat:'Tecralene'}, sizes:['XS','S','M','L','XL'], src:'szacunek z masy i materiału'},
  {id:'fin-cressi-frogplus', cat:'fins', brand:'Cressi', model:'Frog Plus', p:{b:-0.3, mass:1600, mat:'termoguma'}, sizes:['XS','S','M','L','XL'], src:'szacunek z masy i materiału'},
  {id:'fin-cressi-prolight', cat:'fins', brand:'Cressi', model:'Pro Light', p:{b:-0.1, mass:1200, mat:'polipropylen'}, sizes:['XS','S','M','L','XL'], src:'szacunek z masy i materiału'},
  {id:'fin-cressi-reaction', cat:'fins', brand:'Cressi', model:'Reaction EBS', p:{b:-0.1, mass:1400, mat:'polipropylen'}, sizes:['XS','S','M','L','XL'], src:'szacunek z masy i materiału'},
  {id:'fin-tusa-solla', cat:'fins', brand:'Tusa', model:'Solla', p:{b:0.0, mass:1300, mat:'polimer'}, sizes:['XS','S','M','L','XL'], src:'szacunek z masy i materiału'},
  {id:'fin-tusa-hyflex', cat:'fins', brand:'Tusa', model:'Hyflex Switch', p:{b:0.0, mass:1400, mat:'polimer'}, sizes:['XS','S','M','L','XL'], src:'szacunek z masy i materiału'},
  {id:'fin-tusa-xpert', cat:'fins', brand:'Tusa', model:'X-Pert Zoom', p:{b:-0.1, mass:1500, mat:'polimer'}, sizes:['XS','S','M','L','XL'], src:'szacunek z masy i materiału'},
  {id:'fin-al-storm', cat:'fins', brand:'Aqualung', model:'Storm', p:{b:-0.3, mass:1800, mat:'termoguma'}, sizes:['XS','S','M','L','XL'], src:'szacunek z masy i materiału'},
  {id:'fin-al-phase', cat:'fins', brand:'Aqualung', model:'Phase', p:{b:0.0, mass:1300, mat:'polimer'}, sizes:['XS','S','M','L','XL'], src:'szacunek z masy i materiału'},
  {id:'fin-al-hotshot', cat:'fins', brand:'Aqualung', model:'Hotshot', p:{b:0.1, mass:1100, mat:'polimer'}, sizes:['XS','S','M','L','XL'], src:'szacunek z masy i materiału'},
  {id:'fin-apeks-rk3', cat:'fins', brand:'Apeks', model:'RK3 (guma)', p:{b:-0.6, mass:2200, mat:'guma'}, sizes:['S','M','L','XL'], src:'szacunek z masy i materiału'},
  {id:'fin-hollis-f1', cat:'fins', brand:'Hollis', model:'F1 (guma)', p:{b:-1.2, mass:3000, mat:'guma'}, sizes:['M','L','XL','XXL'], src:'szacunek z masy i materiału'},
  {id:'fin-hollis-f1lt', cat:'fins', brand:'Hollis', model:'F1 LT', p:{b:-0.5, mass:2000, mat:'guma'}, sizes:['M','L','XL','XXL'], src:'szacunek z masy i materiału'},
  {id:'fin-tecline-power', cat:'fins', brand:'Tecline', model:'Power Fins (guma)', p:{b:-0.6, mass:2300, mat:'guma'}, sizes:['S','M','L','XL'], src:'szacunek z masy i materiału'},
  {id:'fin-scubatech-tiara', cat:'fins', brand:'Scubatech', model:'Tiara Pro', p:{b:-0.2, mass:1500, mat:'polimer'}, sizes:['S','M','L','XL'], src:'szacunek z masy i materiału'},
  {id:'fin-scubatech-xpower', cat:'fins', brand:'Scubatech', model:'XPower', p:{b:-0.1, mass:1300, mat:'polimer'}, sizes:['S','M','L','XL'], src:'szacunek z masy i materiału'},
  {id:'misc-fins-rubber', cat:'fins', brand:'Ogólne', model:'Płetwy gumowe (np. Jet Fin)', p:{b:-0.7, mat:'guma'}, sizes:SZ.one, src:'szacunek'},
  {id:'misc-fins-plastic', cat:'fins', brand:'Ogólne', model:'Płetwy plastikowe', p:{b:0, mat:'polimer'}, sizes:SZ.one, src:'szacunek'},
  // --- Drobne ---
  {id:'misc-reg', cat:'misc', brand:'Ogólne', model:'Automat + oktopus + manometr', p:{b:-0.9}, sizes:SZ.one, src:'szacunek'},
  {id:'misc-light', cat:'misc', brand:'Ogólne', model:'Latarka główna', p:{b:-0.3}, sizes:SZ.one, src:'szacunek'},
  {id:'misc-camera', cat:'misc', brand:'Ogólne', model:'Aparat w obudowie', p:{b:0.3}, sizes:SZ.one, src:'wpisz własną wartość'},
];

const CATS = {
  wetsuit:{label:'Pianki', one:'Pianka'},
  over:{label:'Ocieplacze mokre', one:'Ocieplacz'},
  hood:{label:'Kaptury', one:'Kaptur'},
  gloves:{label:'Rękawice', one:'Rękawice'},
  boots:{label:'Buty', one:'Buty'},
  dry:{label:'Suche skafandry', one:'Suchy skafander'},
  under:{label:'Ocieplacze do suchego', one:'Ocieplacz do suchego'},
  bcd:{label:'Kamizelki', one:'Kamizelka'},
  wing:{label:'Skrzydła', one:'Skrzydło'},
  tank:{label:'Butle', one:'Butla'},
  fins:{label:'Płetwy', one:'Płetwy'},
  misc:{label:'Drobne', one:'Drobne'}
};
const CAT_ORDER = ['wetsuit','over','hood','gloves','boots','dry','under','bcd','wing','tank','fins','misc'];

// ===== Akweny: temperatury orientacyjne [sty..gru] =====
const SITE_PRESETS = [
  {id:'redsea', name:'Morze Czerwone (Marsa Alam, Dahab)', rho:1.029,
   ts:[23,22,22,23,25,27,28,29,28,27,26,24], tb:[22,21,21,22,24,26,27,28,27,26,25,23]},
  {id:'malta', name:'Malta, Gozo', rho:1.028,
   ts:[15,15,15,16,19,22,25,26,25,23,20,17], tb:[15,14,14,15,16,17,18,19,20,21,19,16]},
  {id:'croatia', name:'Chorwacja (Adriatyk)', rho:1.028,
   ts:[13,13,13,15,18,22,24,25,23,20,17,15], tb:[13,13,13,13,14,15,16,17,18,18,16,14]},
  {id:'cyprus', name:'Cypr', rho:1.028,
   ts:[17,17,17,18,21,24,27,28,27,25,22,19], tb:[17,16,16,17,18,20,22,24,24,23,21,18]},
  {id:'baltic', name:'Bałtyk', rho:1.005,
   ts:[3,2,3,5,9,14,17,18,15,11,7,4], tb:[4,4,4,4,5,6,7,8,8,8,7,5]},
  {id:'hancza', name:'Hańcza', rho:1.000,
   ts:[3,3,4,7,13,18,21,21,17,12,7,4], tb:[4,4,4,4,5,5,5,5,5,5,5,4]},
  {id:'koparki', name:'Koparki (Jaworzno)', rho:1.000,
   ts:[4,4,4,6,12,18,21,21,17,12,7,4], tb:[4,4,4,5,6,7,8,8,8,7,6,4]},
  {id:'piechcin', name:'Piechcin (kamieniołom)', rho:1.000,
   ts:[3,3,4,8,14,19,22,22,18,12,7,4], tb:[4,4,4,5,6,7,8,8,8,7,6,4]},
  {id:'honoratka', name:'Honoratka', rho:1.000,
   ts:[3,3,4,8,14,19,22,22,18,12,7,4], tb:[4,4,4,6,10,14,16,17,15,11,7,5]},
  {id:'deepspot', name:'Deepspot (basen)', rho:1.000,
   ts:[33,33,33,33,33,33,33,33,33,33,33,33], tb:[32,32,32,32,32,32,32,32,32,32,32,32]}
];
const WATER_TYPES = [
  {rho:1.029, label:'Morze Czerwone · 40‰'},
  {rho:1.028, label:'Morze Śródziemne · 38‰'},
  {rho:1.025, label:'Ocean · 35‰'},
  {rho:1.005, label:'Bałtyk · 7‰'},
  {rho:1.000, label:'Woda słodka'}
];
